language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
  - pypy
  - pypy3
jobs:
  allow_failures:
    - python: pypy3
    - python: '3.8'
install:
  - pip install .[dev]
script:
  - inv cover qa
after_success:
  - pip install coveralls
  - coveralls --rcfile=coverage.rc
  - "./travis-bench-after-success.sh"
before_deploy:
  - inv assets
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: Bhk0mw7iFn+kan/rBdegQe2gbvtTd12hCxZzHwZCCgyu6xCK4UT/6eW6KucT1BP5sOzCteYzRcdg5PBLLwXaKXuSVtGmdZwmQcVRgWuXCA9/9YdPJSCSO3dHoVYpiXP9Tc72qPVi/Wwj9t2U7V8IcGoH4NDJn8XM2dFSYHm/ZhXQCSBcXLjLx7EI1M7yXo4h3tLfEka9+VZ8jdEsP6NATaJIeBqo4X4hZj2n2ux6Q0CyxqQWsTx0iQUsKrML7a5lE9vz7Mk21NkZLb8LAg3lRrYEyC2rIdhXOxDED410MGpwMQDZ8MUF85vB1ri/EFLfcRvbFs8+W0vrqltmABlwoymvmtw4B/lbRyjmArjYKk8CCeK5z5KVx+QICrxXMEG/4CeS5vQCz/0uB+Fzu0Xv44kslOSaFewwow/arke80WzdzecBzAi+HANb1L7hufRb63tkmf0Uz3JX5HplI31FbT/pQoL1pZtFoHC9u3/iqYY39z/3Jv8+gop5ZX1WaIgxBxfCIVqx//p3pq9LYkI8zdFv54tD8UiKKJiwAzMIrYQJLkB5RtKBYxoyBXOdYb0H9vVWISXcwQVuKJiQWO/GDjE1KX3TApHSz73DqMemuG5BYDCf9qIbm49rYY57NyFNvgLJVZCwgrY5J9Otmk+e5sjGo3wkOWOriAO6QH7RqEI=
  on:
    tags: true
  skip_existing: true
  skip_cleanup: true
